version: '2'

services:
    web:
        image: mquandalle/wekan
        links:
            - db:db
        ports:
            - 8081:80
        environment:
            MONGO_URL: mongodb://db
            ROOT_URL: http://192.168.99.100:8081

    db:
        image: mongo
        volumes:
            - data:/data/db

volumes:
    data:
        external: false

