version: '2'

services:
    wekan:
        image: mquandalle/wekan
        links:
            - wekandb:db
        ports:
            - 8081:80
        environment:
            MONGO_URL: mongodb://db
            ROOT_URL: http://192.168.99.100:8081

    wekandb:
        image: mongo
        volumes:
            - wekan-data:/data/db

volumes:
    wekan-data:
        external: false

